kind: "MDDT"
use_amp: True
use_critic: False
learning_starts: 0
batch_size: 256
gradient_steps: 1
stochastic_policy: False
train_task_inference_only: True
eval_tii_steps: 1000
loss_fn: "ce"
eval_context_len: 5
ent_coef: 0.0
offline_steps: ${run_params.total_timesteps}
buffer_max_len_type: "transition"
buffer_size: 2000000
buffer_weight_by: len
target_return_type: predefined
warmup_steps: 0
replay_buffer_kwargs:
  num_workers: 16
  pin_memory: False
  init_top_p: 1
load_path:
  dir_path: ${MODELS_DIR}/multi_domain
  file_name: dt_mediumplus_64.zip
freeze_kwargs:
  exclude_tii_head: True
frozen: True
defaults:
  - huggingface: dt_mediumplus_64
  - data_paths: cw10_v2_cwnet_2M
  - model_kwargs: mdmpdt
huggingface:
  activation_function: gelu
  max_length: 5
