kind: "DT"
learning_starts: 0
batch_size: 64
gradient_steps: 1
stochastic_policy: False
loss_fn: "mse"
eval_context_len: 20
ent_coef: 0.0
offline_steps: ${run_params.total_timesteps}
buffer_max_len_type: "transition"
buffer_size: 80000000 # 8e7
buffer_weight_by: uniform 
target_return_type: predefined
replay_buffer_kwargs:
  num_workers: 8
  pin_memory: False
  init_top_p: 1
defaults:
  - huggingface: dt_medium_64
  - data_paths: mt40_v2_cwnet_2M # all MT50 tasks except the CW10 tasks.
  - model_kwargs: default
huggingface:
  # max_ep_len: 201
  activation_function: gelu
