kind: "MPDT"
use_critic: False
learning_starts: 0
batch_size: 64
gradient_steps: 0
stochastic_policy: True
loss_fn: "mse"
eval_context_len: 20
offline_steps: 0
buffer_max_len_type: "transition"
buffer_size: 1000000 # 20M --> 2M per task
target_return_type: predefined

load_path:
  dir_path: ${MODELS_DIR}
  file_name: model_small64_mt40_v2.zip # DT-small (3 layer, 2 head, embed/head 128)
frozen: True

learnable_prompt: True

defaults:
  - huggingface: dt_medium_64
  - prompt_kwargs: l2p

huggingface:
  # max_ep_len: 201
  output_attentions: True
  activation_function: gelu

prompt_kwargs:
  n_layer: ${agent_params.huggingface.n_layer}
  n_head: ${agent_params.huggingface.n_head}
