kind: "MDMPDT"
use_amp: True
use_critic: False
learning_starts: 0
learning_rate: 0.0001
head_scale: 100
batch_size: 256
gradient_steps: 1
stochastic_policy: False
loss_fn: "ce"
eval_context_len: 5
ent_coef: 0.0
offline_steps: ${run_params.total_timesteps}
buffer_max_len_type: "transition"
buffer_size: 20000000 
buffer_weight_by: len 
target_return_type: predefined
warmup_steps: 0
train_wtp_and_tap: False
replay_buffer_kwargs:
  num_workers: 16
  pin_memory: False
  init_top_p: 1
load_path:
  dir_path: ${MODELS_DIR}/multi_domain
  file_name: cw10_cl_tii_42.zip
frozen: True
freeze_kwargs:
  exclude_action_head: True
defaults:
  - huggingface: dt_mediumplus_64
  - data_paths: cw10_v2_cwnet_2M
  - model_kwargs: mdmpdt
huggingface:
  activation_function: gelu
  max_length: 5
