kind: "DT"
batch_size: 64
stochastic_policy: True
gradient_steps: 0
learning_starts: 0
loss_fn: "mse"
eval_context_len: 20
buffer_max_len_type: "transition"
buffer_size: 1000000
steps_per_task: 1000000 # same as run_params.steps_per_task
target_return_type: predefined
load_path:
  dir_path: ${MODELS_DIR}
  file_name: model_small_mt40_50K_notaskids_cwnet_new.zip # DT-small (3 layer, 2 head, embed/head 128)
frozen: True

use_prompt_buffer: True
separate_prompt_embed: True
prompt_buffer_sync_freq: 1e8 # never
prompt_buffer_kwargs:
  num_seq_per_prompt: 1
  num_trjs_per_task: 10
  init_top_p: 0.002 # amounts to 20 trajectories

defaults:
  - huggingface: dt_medium_64
  - prompt_data_paths: cw10_v2_cwnet_2M
huggingface:
  # max_ep_len: 201
  activation_function: gelu