envid: cheetah-run
reward_scale: 100
target_return: 1000
num_envs: 1
norm_obs: False
record: False
record_freq: 250000
record_length: 1000
eval_env_names: "dmcontrol_visual"
dmc_env_kwargs: 
  from_pixels: True
  visualize_reward: False
  frame_skip: 2
