reward_condition: True
tokenize_a: True
tokenize_rtg: False 
action_channels: 64
discrete_actions: 0
state_dim: 204
image_shape: 
relative_pos_embds: False
learnable_prompt: True
defaults: 
  - prompt_kwargs: l2p
prompt_kwargs:
  n_layer: ${agent_params.huggingface.n_layer}
  n_head: ${agent_params.huggingface.n_head}