reward_condition: True
tokenize_a: False
relative_pos_embds: True
learnable_prompt: True
defaults: 
  - prompt_kwargs: l2p
prompt_kwargs:
  n_layer: ${agent_params.huggingface.n_layer}
  n_head: ${agent_params.huggingface.n_head}