- hammer-v1.npz
- push-wall-v1.npz
- faucet-close-v1.npz
- push-back-v1.npz
- stick-pull-v1.npz
- handle-press-side-v1.npz
- push-v1.npz
- shelf-place-v1.npz
- window-close-v1.npz
- peg-unplug-side-v1.npz
