- hammer-v2.pkl
- push-wall-v2.pkl
- faucet-close-v2.pkl
- push-back-v2.pkl
- stick-pull-v2.pkl
- handle-press-side-v2.pkl
- push-v2.pkl
- shelf-place-v2.pkl
- window-close-v2.pkl
- peg-unplug-side-v2.pkl
