- hammer-v1.pkl
- push-wall-v1.pkl
- faucet-close-v1.pkl
- push-back-v1.pkl
- stick-pull-v1.pkl
- handle-press-side-v1.pkl
- push-v1.pkl
- shelf-place-v1.pkl
- window-close-v1.pkl
- peg-unplug-side-v1.pkl