- cartpole_balance.npz
- finger_turn_easy.npz 
- finger_turn_hard.npz 
- fish_upright.npz
- hopper_stand.npz
- pendulum_swingup.npz 
- point_mass_easy.npz 
- reacher_hard.npz
- walker_stand.npz
- walker_run.npz