- assembly-v1.npz
- button-press-v1.npz
- disassemble-v1.npz
- plate-slide-side-v1.npz
- door-lock-v1.npz
- door-unlock-v1.npz
- pick-place-v1.npz
- drawer-close-v1.npz
- coffee-pull-v1.npz
- handle-pull-v1.npz
- peg-insert-side-v1.npz
- door-close-v1.npz
- button-press-topdown-v1.npz
- lever-pull-v1.npz
- reach-v1.npz
- door-open-v1.npz
- sweep-v1.npz
- box-close-v1.npz
- button-press-wall-v1.npz
- basketball-v1.npz
- soccer-v1.npz
- handle-press-v1.npz
- coffee-button-v1.npz
- faucet-open-v1.npz
- plate-slide-v1.npz
- reach-wall-v1.npz
- handle-pull-side-v1.npz
- drawer-open-v1.npz
- dial-turn-v1.npz
- sweep-into-v1.npz
- bin-picking-v1.npz
- coffee-push-v1.npz
- pick-out-of-hole-v1.npz
- button-press-topdown-wall-v1.npz
- plate-slide-back-side-v1.npz
- plate-slide-back-v1.npz
- stick-push-v1.npz
- hand-insert-v1.npz
- window-open-v1.npz
- pick-place-wall-v1.npz
