- assembly-v1.pkl
- button-press-v1.pkl
- disassemble-v1.pkl
- plate-slide-side-v1.pkl
- door-lock-v1.pkl
- door-unlock-v1.pkl
- pick-place-v1.pkl
- drawer-close-v1.pkl
- coffee-pull-v1.pkl
- handle-pull-v1.pkl
- peg-insert-side-v1.pkl
- door-close-v1.pkl
- button-press-topdown-v1.pkl
- lever-pull-v1.pkl
- reach-v1.pkl
- door-open-v1.pkl
- sweep-v1.pkl
- box-close-v1.pkl
- button-press-wall-v1.pkl
- basketball-v1.pkl
- soccer-v1.pkl
- handle-press-v1.pkl
- coffee-button-v1.pkl
- faucet-open-v1.pkl
- plate-slide-v1.pkl
- reach-wall-v1.pkl
- handle-pull-side-v1.pkl
- drawer-open-v1.pkl
- dial-turn-v1.pkl
- sweep-into-v1.pkl
- bin-picking-v1.pkl
- coffee-push-v1.pkl
- pick-out-of-hole-v1.pkl
- button-press-topdown-wall-v1.pkl
- plate-slide-back-side-v1.pkl
- plate-slide-back-v1.pkl
- stick-push-v1.pkl
- hand-insert-v1.pkl
- window-open-v1.pkl
- pick-place-wall-v1.pkl