- assembly-v2.npz
- button-press-v2.npz
- disassemble-v2.npz
- plate-slide-side-v2.npz
- door-lock-v2.npz
- door-unlock-v2.npz
- pick-place-v2.npz
- drawer-close-v2.npz
- coffee-pull-v2.npz
- handle-pull-v2.npz
- peg-insert-side-v2.npz
- door-close-v2.npz
- button-press-topdown-v2.npz
- lever-pull-v2.npz
- reach-v2.npz
- door-open-v2.npz
- sweep-v2.npz
- box-close-v2.npz
- button-press-wall-v2.npz
- basketball-v2.npz
- soccer-v2.npz
- handle-press-v2.npz
- coffee-button-v2.npz
- faucet-open-v2.npz
- plate-slide-v2.npz
- reach-wall-v2.npz
- handle-pull-side-v2.npz
- drawer-open-v2.npz
- dial-turn-v2.npz
- sweep-into-v2.npz
- bin-picking-v2.npz
- coffee-push-v2.npz
- pick-out-of-hole-v2.npz
- button-press-topdown-wall-v2.npz
- plate-slide-back-side-v2.npz
- plate-slide-back-v2.npz
- stick-push-v2.npz
- hand-insert-v2.npz
- window-open-v2.npz
- pick-place-wall-v2.npz
- hammer-v2.npz
- peg-unplug-side-v2.npz
- window-close-v2.npz
- faucet-close-v2.npz
- handle-press-side-v2.npz
- push-back-v2.npz
- push-v2.npz
- push-wall-v2.npz
- stick-pull-v2.npz
- shelf-place-v2.npz
