# Hydra does not support having multiple defaults lists in the same file
# therefore, need to paste in all names here
mt40_v2:
  base: ${DATA_DIR}/metaworld_v2_cwnet_2M
  names:
    - hammer-v2.npz
    - push-wall-v2.npz
    - faucet-close-v2.npz
    - push-back-v2.npz
    - stick-pull-v2.npz
    - handle-press-side-v2.npz
    - push-v2.npz
    - shelf-place-v2.npz
    - window-close-v2.npz
    - peg-unplug-side-v2.npz

atari:
  base: ${SSD_DATA_DIR}/atari_1M
  names:
    # same ones as used in MGDT
    - alien
    - ms-pacman
    - pong
    - space-invaders
    - star-gunner
