# Hydra does not support having multiple defaults lists in the same file
# therefore, need to paste in all names here
cw10_v2: 
  base: ${DATA_DIR}/metaworld_v2_cwnet_2M
  names: 
    - hammer-v2.pkl
    - push-wall-v2.pkl
    - faucet-close-v2.pkl
    - push-back-v2.pkl
    - stick-pull-v2.pkl
    - handle-press-side-v2.pkl
    - push-v2.pkl
    - shelf-place-v2.pkl
    - window-close-v2.pkl
    - peg-unplug-side-v2.pkl 
    

dmc10: 
  base: ${DATA_DIR}/dm_control_1M_v3_full
  names: 
    - ball_in_cup_catch.npz
    - cartpole_swingup.npz
    - cheetah_run.npz
    - finger_spin.npz
    - reacher_hard.npz 
    - walker_walk.npz
