# Hydra does not support having multiple defaults lists in the same file
# therefore, need to paste in all names here
cw10_v2:
  base: ${DATA_DIR}/metaworld_v2_cwnet_2M
  names:
    - hammer-v2.npz
    - push-wall-v2.npz
    - faucet-close-v2.npz
    - push-back-v2.npz
    - stick-pull-v2.npz
    - handle-press-side-v2.npz
    - push-v2.npz
    - shelf-place-v2.npz
    - window-close-v2.npz
    - peg-unplug-side-v2.npz

dmc10:
  base: ${DATA_DIR}/dm_control_1M_v3_full
  names:
    - ball_in_cup_catch.npz
    - cartpole_swingup.npz
    - cheetah_run.npz
    - finger_spin.npz
    - reacher_hard.npz
    - walker_walk.npz
